import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { analyticsApi } from '../../lib/masterDataApi.js'; import { formatMoney } from '../../lib/format.js'; import { PageHeader } from '../../components/PageHeader.jsx';
function Cards({items}){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map(([l,v])=><div key={l} className="rounded-2xl bg-white p-5 shadow-card"><p className="text-xs font-bold uppercase text-muted">{l}</p><p className="mt-2 text-xl font-bold text-navy">{formatMoney(v)}</p></div>)}</div>}
function Load({load,children}){const[d,setD]=useState(null),[e,setE]=useState('');useEffect(()=>{load().then(setD).catch(x=>setE(x.message));},[]);if(e)return <div className="rounded-xl bg-danger/10 p-4 text-danger">Unable to load analytics: {e}</div>;return d?children(d):<div className="rounded-xl bg-white p-5 text-muted shadow-card">Loading live analytics…</div>}
function Aging({title,load,party,link}){return <div><PageHeader title={title} subtitle="Posted documents and recorded payments only"/><Load load={load}>{d=><div className="space-y-5"><Cards items={[["Outstanding",d.outstanding],["Current",d.current],["1–30 days",d.days1To30],["90+ days",d.days90Plus]]}/><div className="overflow-x-auto rounded-2xl bg-white p-5 shadow-card"><h2 className="mb-3 font-bold text-ink">{party} outstanding</h2>{d[party.toLowerCase()]?.length?<table className="w-full min-w-[620px] text-sm"><thead><tr className="text-left text-muted"><th>{party}</th><th>Documents</th><th>Outstanding</th><th>Overdue</th><th>Oldest due</th></tr></thead><tbody>{d[party.toLowerCase()].map(x=><tr key={x.id} className="border-t border-slate-100"><td className="py-3"><Link className="font-semibold text-indigo" to={`${link}/${x.id}`}>{x.name}</Link></td><td>{x.documentCount}</td><td>{formatMoney(x.outstanding)}</td><td className="text-danger">{formatMoney(x.overdue)}</td><td>{x.oldestDueDate||'—'}</td></tr>)}</tbody></table>:<p className="text-muted">No outstanding {party.toLowerCase()} balances.</p>}</div></div>}</Load></div>}
export const ReceivablesPage=()=> <Aging title="Receivables Analytics" load={analyticsApi.receivables} party="Customers" link="/master-data/contacts"/>;
export const PayablesPage=()=> <Aging title="Payables Analytics" load={analyticsApi.payables} party="Vendors" link="/master-data/contacts"/>;
export function CashFlowPage(){return <div><PageHeader title="Cash Flow Analytics" subtitle="Customer receipts and vendor payments"/><Load load={analyticsApi.cashFlow}>{d=><div className="space-y-5"><Cards items={[["Cash inflows",d.inflows],["Cash outflows",d.outflows],["Net movement",d.netCashFlow]]}/><div className="h-72 rounded-2xl bg-white p-5 shadow-card"><ResponsiveContainer><BarChart data={d.trend}><XAxis dataKey="date"/><YAxis/><Tooltip formatter={v=>formatMoney(v)}/><Bar dataKey="inflows" fill="#4f9d74"/><Bar dataKey="outflows" fill="#d46a6a"/></BarChart></ResponsiveContainer></div></div>}</Load></div>}
export function TrendsPage(){return <div><PageHeader title="Profitability Trend" subtitle="Revenue and expenses from posted journal entries"/><Load load={analyticsApi.trends}>{d=><div className="h-80 rounded-2xl bg-white p-5 shadow-card">{d.trend.length?<ResponsiveContainer><BarChart data={d.trend}><XAxis dataKey="period"/><YAxis/><Tooltip formatter={v=>formatMoney(v)}/><Bar dataKey="revenue" fill="#545b9a"/><Bar dataKey="expenses" fill="#d46a6a"/></BarChart></ResponsiveContainer>:<p className="text-muted">No posted activity for this period.</p>}</div>}</Load></div>}
