import { useEffect, useState } from 'react';
import { PageHeader } from '../../components/PageHeader.jsx';
import { Table, Td, Th, Tr } from '../../components/Table.jsx';
import { Button } from '../../components/Button.jsx';
import { EmptyState, LoadingTable } from '../../components/DataStates.jsx';
import { formatDate, formatMoney } from '../../lib/format.js';
import { purchasesApi } from '../../lib/masterDataApi.js';
export function PurchaseOrdersPage(){const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const load=()=>{setLoading(true);purchasesApi.orders().then(d=>setRows(d.purchaseOrders||[])).finally(()=>setLoading(false));};useEffect(load,[]);return <PurchaseList title="Purchase Orders" subtitle="Vendor orders before supplier billing" rows={rows} loading={loading} columns={['PO Number','Vendor','Date','Total','Status']} render={r=><Tr key={r.id}><Td first className="font-semibold text-navy">{r.orderNumber}</Td><Td>{r.vendorName}</Td><Td>{formatDate(r.orderDate)}</Td><Td>{formatMoney(r.totalAmount)}</Td><Td last>{r.status}</Td></Tr>}/>}
export function VendorBillsPage(){const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);useEffect(()=>{purchasesApi.bills().then(d=>setRows(d.vendorBills||[])).finally(()=>setLoading(false));},[]);return <PurchaseList title="Vendor Bills" subtitle="Supplier bills and their accounting state" rows={rows} loading={loading} columns={['Bill Number','Vendor','Invoice','Due Date','Total','Status']} render={r=><Tr key={r.id}><Td first className="font-semibold text-navy">{r.billNumber}</Td><Td>{r.vendorName}</Td><Td>{r.vendorInvoiceNumber||'—'}</Td><Td>{formatDate(r.dueDate)}</Td><Td>{formatMoney(r.totalAmount)}</Td><Td last>{r.status} · {r.paymentStatus}</Td></Tr>}/>}
function PurchaseList({title,subtitle,rows,loading,columns,render}){return <div><PageHeader title={title} subtitle={subtitle}/><div className="rounded-2xl border border-white/80 bg-white p-5 shadow-card">{loading?<LoadingTable columns={columns.length}/>:rows.length===0?<EmptyState title={`No ${title.toLowerCase()} found.`}/>:<Table><thead><tr>{columns.map(c=><Th key={c}>{c}</Th>)}</tr></thead><tbody>{rows.map(render)}</tbody></Table>}</div></div>}
