const reports = require('./reportingService');

const money = (value) => Number(value || 0).toFixed(2);
const dates = (q) => ({ startDate: q.startDate || null, endDate: q.endDate || null });
const clause = (params, field, startDate, endDate) => {
  const where = [];
  if (startDate) { params.push(startDate); where.push(`${field} >= $${params.length}`); }
  if (endDate) { params.push(endDate); where.push(`${field} <= $${params.length}`); }
  return where.length ? ` AND ${where.join(' AND ')}` : '';
};

async function sales(db, q = {}) {
  const { startDate, endDate } = dates(q); const p = [];
  const filter = clause(p, 'i.invoice_date', startDate, endDate);
  const totals = await db.query(`SELECT COUNT(*) FILTER (WHERE status='POSTED')::int AS "invoiceCount",COALESCE(SUM(total_amount) FILTER (WHERE status='POSTED'),0)::text AS "totalSales",COUNT(*) FILTER (WHERE status='POSTED' AND payment_status='PAID')::int AS "paidInvoices",COUNT(*) FILTER (WHERE status='POSTED' AND payment_status<>'PAID')::int AS "unpaidInvoices",COUNT(*) FILTER (WHERE status='POSTED' AND due_date<CURRENT_DATE AND payment_status<>'PAID')::int AS "overdueInvoices",COALESCE(SUM(total_amount) FILTER (WHERE status='POSTED'),0)::numeric-COALESCE((SELECT SUM(amount) FROM payments WHERE status='POSTED' AND type='CUSTOMER'),0)::numeric AS outstanding FROM customer_invoices i WHERE true${filter}`, p);
  const products = await db.query(`SELECT p.id,p.name,COALESCE(SUM(li.quantity),0)::text AS quantity,COALESCE(SUM(li.line_subtotal),0)::text AS revenue FROM customer_invoice_items li JOIN customer_invoices i ON i.id=li.customer_invoice_id JOIN products p ON p.id=li.product_id WHERE i.status='POSTED'${filter} GROUP BY p.id ORDER BY SUM(li.line_subtotal) DESC LIMIT 5`, p);
  const customers = await db.query(`SELECT c.id,c.name,COUNT(i.id)::int AS "invoiceCount",COALESCE(SUM(i.total_amount),0)::text AS sales FROM customer_invoices i JOIN contacts c ON c.id=i.customer_id WHERE i.status='POSTED'${filter} GROUP BY c.id ORDER BY SUM(i.total_amount) DESC LIMIT 5`, p);
  const t = totals.rows[0]; return { ...t, totalSales: money(t.totalSales), outstanding: money(t.outstanding), averageInvoiceValue: money(Number(t.totalSales) / (t.invoiceCount || 1)), topProducts: products.rows, topCustomers: customers.rows, filters: { startDate, endDate } };
}

async function purchases(db, q = {}) {
  const { startDate, endDate } = dates(q); const p = []; const filter = clause(p, 'b.invoice_date', startDate, endDate);
  const totals = await db.query(`SELECT COUNT(*) FILTER (WHERE status='POSTED')::int AS "billCount",COALESCE(SUM(total_amount) FILTER (WHERE status='POSTED'),0)::text AS "totalPurchases",COALESCE(SUM(total_amount) FILTER (WHERE status='POSTED'),0)::numeric-COALESCE((SELECT SUM(amount) FROM payments WHERE status='POSTED' AND type='VENDOR'),0)::numeric AS outstanding FROM vendor_bills b WHERE true${filter}`,p);
  const vendors = await db.query(`SELECT c.id,c.name,COALESCE(SUM(b.total_amount),0)::text AS purchases FROM vendor_bills b JOIN contacts c ON c.id=b.vendor_id WHERE b.status='POSTED'${filter} GROUP BY c.id ORDER BY SUM(b.total_amount) DESC LIMIT 5`,p);
  const t=totals.rows[0]; return {...t,totalPurchases:money(t.totalPurchases),outstanding:money(t.outstanding),topVendors:vendors.rows,filters:{startDate,endDate}};
}

async function inventory(db) { const r=await db.query(`SELECT COUNT(*)::int AS "totalProducts",COUNT(*) FILTER (WHERE COALESCE(s.quantity,0)>5)::int AS "inStockProducts",COUNT(*) FILTER (WHERE COALESCE(s.quantity,0)>0 AND COALESCE(s.quantity,0)<=5)::int AS "lowStockProducts",COUNT(*) FILTER (WHERE COALESCE(s.quantity,0)=0)::int AS "outOfStockProducts",COALESCE(SUM(s.quantity),0)::text AS "totalUnits",COALESCE(SUM(s.quantity*s.average_cost),0)::text AS "inventoryValue" FROM products p LEFT JOIN inventory_stock s ON s.product_id=p.id WHERE p.type='GOODS'`); const alerts=await db.query(`SELECT p.id,p.name,COALESCE(s.quantity,0)::text AS quantity FROM products p LEFT JOIN inventory_stock s ON s.product_id=p.id WHERE p.type='GOODS' AND COALESCE(s.quantity,0)<=5 ORDER BY s.quantity,p.name LIMIT 10`); return {...r.rows[0],inventoryValue:money(r.rows[0].inventoryValue),alerts:alerts.rows}; }

async function aging(db, type) { const invoice=type==='CUSTOMER'?'customer_invoices':'vendor_bills',party=type==='CUSTOMER'?'customer':'vendor'; const column=type==='CUSTOMER'?'customer_invoice_id':'vendor_bill_id'; const rows=await db.query(`WITH open_docs AS (SELECT d.id,d.${party}_id AS party_id,d.due_date,d.total_amount,d.payment_status,d.total_amount-COALESCE((SELECT SUM(amount) FROM payments p WHERE p.${column}=d.id AND p.status='POSTED'),0) AS outstanding FROM ${invoice} d WHERE d.status='POSTED') SELECT COALESCE(SUM(outstanding) FILTER (WHERE outstanding>0),0)::text AS outstanding,COUNT(*) FILTER (WHERE outstanding>0)::int AS "outstandingCount",COUNT(*) FILTER (WHERE payment_status='UNPAID')::int AS "unpaidCount",COUNT(*) FILTER (WHERE payment_status='PARTIALLY_PAID')::int AS "partiallyPaidCount",COUNT(*) FILTER (WHERE payment_status='PAID')::int AS "paidCount",COUNT(*) FILTER (WHERE due_date<CURRENT_DATE AND outstanding>0)::int AS "overdueCount",COALESCE(SUM(outstanding) FILTER (WHERE due_date>=CURRENT_DATE AND outstanding>0),0)::text AS current,COALESCE(SUM(outstanding) FILTER (WHERE CURRENT_DATE-due_date BETWEEN 1 AND 30 AND outstanding>0),0)::text AS "days1To30",COALESCE(SUM(outstanding) FILTER (WHERE CURRENT_DATE-due_date BETWEEN 31 AND 60 AND outstanding>0),0)::text AS "days31To60",COALESCE(SUM(outstanding) FILTER (WHERE CURRENT_DATE-due_date BETWEEN 61 AND 90 AND outstanding>0),0)::text AS "days61To90",COALESCE(SUM(outstanding) FILTER (WHERE CURRENT_DATE-due_date>90 AND outstanding>0),0)::text AS "days90Plus" FROM open_docs`); const parties=await db.query(`WITH open_docs AS (SELECT d.${party}_id party_id,d.due_date,d.total_amount-COALESCE((SELECT SUM(amount) FROM payments p WHERE p.${column}=d.id AND p.status='POSTED'),0) outstanding FROM ${invoice} d WHERE d.status='POSTED') SELECT c.id,c.name,COUNT(*) FILTER(WHERE o.outstanding>0)::int AS "documentCount",COALESCE(SUM(o.outstanding) FILTER(WHERE o.outstanding>0),0)::text AS outstanding,COALESCE(SUM(o.outstanding) FILTER(WHERE o.due_date<CURRENT_DATE AND o.outstanding>0),0)::text AS overdue,MIN(o.due_date) FILTER(WHERE o.outstanding>0) AS "oldestDueDate" FROM open_docs o JOIN contacts c ON c.id=o.party_id GROUP BY c.id ORDER BY SUM(o.outstanding) DESC LIMIT 25`); return {...rows.rows[0],customers:parties.rows,vendors:parties.rows}; }
async function receivables(db){return aging(db,'CUSTOMER');}
async function payables(db){return aging(db,'VENDOR');}
async function cashFlow(db,q={}) { const {startDate,endDate}=dates(q);const p=[];const filter=clause(p,'payment_date',startDate,endDate);const totals=await db.query(`SELECT COALESCE(SUM(amount) FILTER(WHERE type='CUSTOMER' AND status='POSTED'),0)::text AS inflows,COALESCE(SUM(amount) FILTER(WHERE type='VENDOR' AND status='POSTED'),0)::text AS outflows FROM payments WHERE true${filter}`,p);const trend=await db.query(`SELECT payment_date::text AS date,COALESCE(SUM(amount) FILTER(WHERE type='CUSTOMER' AND status='POSTED'),0)::text AS inflows,COALESCE(SUM(amount) FILTER(WHERE type='VENDOR' AND status='POSTED'),0)::text AS outflows FROM payments WHERE true${filter} GROUP BY payment_date ORDER BY payment_date`,p);const t=totals.rows[0];return{inflows:money(t.inflows),outflows:money(t.outflows),netCashFlow:money(Number(t.inflows)-Number(t.outflows)),trend:trend.rows,filters:{startDate,endDate}}; }
async function trends(db,q={}) { const {startDate,endDate}=dates(q);const p=[];const filter=clause(p,'e.entry_date',startDate,endDate);const rows=await db.query(`SELECT date_trunc('month',e.entry_date)::date::text AS period,COALESCE(SUM(l.credit-l.debit) FILTER(WHERE a.type='INCOME'),0)::text AS revenue,COALESCE(SUM(l.debit-l.credit) FILTER(WHERE a.type='EXPENSE'),0)::text AS expenses FROM journal_entries e JOIN journal_entry_lines l ON l.journal_entry_id=e.id JOIN accounts a ON a.id=l.account_id WHERE e.status='POSTED'${filter} GROUP BY 1 ORDER BY 1`,p);return{trend:rows.rows,filters:{startDate,endDate}}; }

// Month-by-month series for the AI assistant's "sales trend" / "purchase
// trend" tools and for future dedicated analytics pages. Filters on the
// document's own status column via a plain WHERE clause (not a join
// condition), so this can't repeat the draft-leakage bug fixed in
// reportingService.
async function salesTrends(db,q={}) { const {startDate,endDate}=dates(q);const p=[];const filter=clause(p,'i.invoice_date',startDate,endDate);const rows=await db.query(`SELECT date_trunc('month',i.invoice_date)::date::text AS period,COALESCE(SUM(i.total_amount),0)::text AS sales,COUNT(*)::int AS "invoiceCount" FROM customer_invoices i WHERE i.status='POSTED'${filter} GROUP BY 1 ORDER BY 1`,p);return{trend:rows.rows,filters:{startDate,endDate}}; }
async function purchaseTrends(db,q={}) { const {startDate,endDate}=dates(q);const p=[];const filter=clause(p,'b.invoice_date',startDate,endDate);const rows=await db.query(`SELECT date_trunc('month',b.invoice_date)::date::text AS period,COALESCE(SUM(b.total_amount),0)::text AS purchases,COUNT(*)::int AS "billCount" FROM vendor_bills b WHERE b.status='POSTED'${filter} GROUP BY 1 ORDER BY 1`,p);return{trend:rows.rows,filters:{startDate,endDate}}; }

async function dashboard(db,q={}) { const [pl,bs,salesData,purchaseData,stock,budgetData,activity] = await Promise.all([reports.profitLoss(db,q),reports.balanceSheet(db,{endDate:q.endDate}),sales(db,q),purchases(db,q),inventory(db),reports.budget(db,q),db.query(`SELECT action,entity,entity_id AS "entityId",timestamp FROM audit_logs ORDER BY timestamp DESC LIMIT 8`)]); const assets=[...bs.assets]; const value=(code)=>money(assets.find(x=>x.accountCode===code)?.amount); return { kpis:{totalRevenue:pl.totalRevenue,totalExpenses:pl.totalExpenses,netProfit:pl.netProfit,cashBalance:value('1001'),bankBalance:value('1002'),receivables:value('1003'),payables:money(bs.liabilities.find(x=>x.accountCode==='2001')?.amount),inventoryValue:stock.inventoryValue}, sales:salesData,purchases:purchaseData,inventory:stock,budget:budgetData.budgets,activity:activity.rows,filters:{startDate:q.startDate||null,endDate:q.endDate||null} }; }
module.exports={dashboard,sales,purchases,inventory,receivables,payables,cashFlow,trends,salesTrends,purchaseTrends};
