const { randomUUID } = require('crypto');
const { withTransaction } = require('../db/transaction');
const { logAudit } = require('../db/audit');
const accounting = require('./accountingService');
const TAX_RATES = [0, 5, 12, 18, 28];
const bad = (message, status = 400) => Object.assign(new Error(message), { status });
function lines(raw) { if (!Array.isArray(raw) || !raw.length) throw bad('Sales Order must contain at least one item.'); return raw.map((l, i) => { const quantity=Number(l.quantity), price=Number(l.unitPrice), tax=Number(l.taxRate || 0); if (!l.productId) throw bad(`Item ${i+1} product is required.`); if (!Number.isFinite(quantity)||quantity<=0) throw bad('Quantity must be greater than zero.'); if (!Number.isFinite(price)||price<0) throw bad('Unit price cannot be negative.'); if (!TAX_RATES.includes(tax)) throw bad('Tax rate is invalid.'); const subtotal=quantity*price, taxAmount=subtotal*tax/100; return {...l,quantity,price,tax,subtotal,taxAmount,total:subtotal+taxAmount}; }); }
function totals(items) { return items.reduce((r,i)=>({subtotal:r.subtotal+i.subtotal,tax:r.tax+i.taxAmount,total:r.total+i.total}),{subtotal:0,tax:0,total:0}); }
async function refs(db, customerId, items) { const c=await db.query("SELECT id FROM contacts WHERE id=$1 AND status='ACTIVE' AND type IN ('CUSTOMER','BOTH')",[customerId]); if(!c.rowCount) throw bad('Selected contact is not a valid active customer.'); for(const i of items){const p=await db.query("SELECT id FROM products WHERE id=$1 AND status='ACTIVE'",[i.productId]);if(!p.rowCount)throw bad('Product is archived and cannot be used for a new Sales Order.');} }
async function insert(db, table, parent, id, items) { for(const [n,i] of items.entries()) await db.query(`INSERT INTO ${table} (id,${parent},product_id,description,quantity,unit_price,tax_rate,tax_amount,line_subtotal,line_total,line_order) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[randomUUID(),id,i.productId,i.description||null,i.quantity,i.price,i.tax,i.taxAmount,i.subtotal,i.total,n+1]); }
async function createOrder(db,userId,b){const items=lines(b.items),t=totals(items);if(!b.customerId||!b.orderDate)throw bad('Customer and order date are required.');return withTransaction(db,async tx=>{await refs(tx,b.customerId,items);const n=await tx.query("SELECT nextval('sales_order_number_seq') n"),id=randomUUID(),number=`SO-${String(n.rows[0].n).padStart(6,'0')}`;await tx.query('INSERT INTO sales_orders (id,order_number,customer_id,order_date,expected_date,reference,notes,subtotal,tax_amount,total_amount,created_by_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id,number,b.customerId,b.orderDate,b.expectedDate||null,b.reference||null,b.notes||null,t.subtotal,t.tax,t.total,userId]);await insert(tx,'sales_order_items','sales_order_id',id,items);await logAudit(tx,{userId,action:'SALES_ORDER_CREATED',entity:'SalesOrder',entityId:id});return {id,orderNumber:number,status:'DRAFT',subtotal:t.subtotal.toFixed(2),taxAmount:t.tax.toFixed(2),totalAmount:t.total.toFixed(2)};});}
async function confirmOrder(db,id,userId){const r=await db.query("UPDATE sales_orders SET status='CONFIRMED',confirmed_by_id=$1,confirmed_at=NOW(),updated_at=NOW() WHERE id=$2 AND status='DRAFT' RETURNING id,order_number AS \"orderNumber\"",[userId,id]);if(!r.rowCount)throw bad('Only Draft Sales Orders can be confirmed.');await logAudit(db,{userId,action:'SALES_ORDER_CONFIRMED',entity:'SalesOrder',entityId:id});return r.rows[0];}
async function createInvoice(db,userId,b){const items=lines(b.items),t=totals(items);if(!b.customerId||!b.invoiceDate||!b.dueDate)throw bad('Customer, invoice date, and due date are required.');if(b.dueDate<b.invoiceDate)throw bad('Due date cannot be before invoice date.');return withTransaction(db,async tx=>{await refs(tx,b.customerId,items);const n=await tx.query("SELECT nextval('customer_invoice_number_seq') n"),id=randomUUID(),number=`INV-${String(n.rows[0].n).padStart(6,'0')}`;await tx.query('INSERT INTO customer_invoices (id,invoice_number,customer_id,sales_order_id,invoice_date,due_date,reference,notes,subtotal,tax_amount,total_amount,created_by_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[id,number,b.customerId,b.salesOrderId||null,b.invoiceDate,b.dueDate,b.reference||null,b.notes||null,t.subtotal,t.tax,t.total,userId]);await insert(tx,'customer_invoice_items','customer_invoice_id',id,items);await logAudit(tx,{userId,action:'CUSTOMER_INVOICE_CREATED',entity:'CustomerInvoice',entityId:id});return {id,invoiceNumber:number,status:'DRAFT',paymentStatus:'UNPAID',totalAmount:t.total.toFixed(2)};});}
async function postInvoice(db,id,userId){const inv=await db.query("SELECT * FROM customer_invoices WHERE id=$1",[id]);if(!inv.rowCount)throw bad('Customer Invoice not found.',404);const b=inv.rows[0];if(b.status!=='DRAFT')throw bad('Only Draft Customer Invoices can be posted.');const accounts=await db.query("SELECT id,account_code FROM accounts WHERE status='ACTIVE' AND account_code IN ('1003','4001','2002')"),map=Object.fromEntries(accounts.rows.map(a=>[a.account_code,a.id]));const journal=await db.query("SELECT id FROM journals WHERE type='SALES' AND status='ACTIVE' LIMIT 1");if(!map['1003']||!map['4001']||!journal.rowCount||(+b.tax_amount>0&&!map['2002']))throw bad('Sales Journal, Debtors, Sales Income, and Output Tax Payable must be configured.');const entryLines=[{accountId:map['1003'],debit:String(b.total_amount),credit:'0'},{accountId:map['4001'],debit:'0',credit:String(b.subtotal)}];if(+b.tax_amount>0)entryLines.push({accountId:map['2002'],debit:'0',credit:String(b.tax_amount)});const entry=await accounting.createDraftEntry(db,userId,{journalId:journal.rows[0].id,entryDate:b.invoice_date,reference:b.invoice_number,description:`Customer Invoice ${b.invoice_number}`,lines:entryLines});await accounting.postEntry(db,entry.id,userId);await db.query("UPDATE customer_invoices SET status='POSTED',payment_status='UNPAID',posted_by_id=$1,posted_at=NOW(),accounting_entry_id=$2 WHERE id=$3 AND status='DRAFT'",[userId,entry.id,id]);await logAudit(db,{userId,action:'CUSTOMER_INVOICE_POSTED',entity:'CustomerInvoice',entityId:id,metadata:{accountingEntryId:entry.id}});return {id,status:'POSTED',accountingEntryId:entry.id};}
module.exports={createOrder,confirmOrder,createInvoice,postInvoice,lines,totals};
