import { useEffect, useState } from 'react';
import { PageHeader } from '../../components/PageHeader.jsx';
import { EmptyState, LoadingTable } from '../../components/DataStates.jsx';
import { Table, Td, Th, Tr } from '../../components/Table.jsx';
import { formatDate, formatMoney } from '../../lib/format.js';
import { salesApi } from '../../lib/masterDataApi.js';
export function SalesOrdersPage(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{salesApi.orders().then(x=>setRows(x.salesOrders||[])).finally(()=>setLoading(false));},[]);return <SalesTable title="Sales Orders" subtitle="Commercial customer orders with no accounting impact until invoiced" rows={rows} loading={loading} headers={['SO Number','Customer','Date','Total','Status']} cells={r=><Tr key={r.id}><Td first className="font-semibold text-navy">{r.orderNumber}</Td><Td>{r.customerName}</Td><Td>{formatDate(r.orderDate)}</Td><Td>{formatMoney(r.totalAmount)}</Td><Td last>{r.status}</Td></Tr>}/>}
export function CustomerInvoicesPage(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{salesApi.invoices().then(x=>setRows(x.customerInvoices||[])).finally(()=>setLoading(false));},[]);return <SalesTable title="Customer Invoices" subtitle="Draft and posted receivable documents" rows={rows} loading={loading} headers={['Invoice','Customer','Date','Total','Status']} cells={r=><Tr key={r.id}><Td first className="font-semibold text-navy">{r.invoiceNumber}</Td><Td>{r.customerName}</Td><Td>{formatDate(r.invoiceDate)}</Td><Td>{formatMoney(r.totalAmount)}</Td><Td last>{r.status} · {r.paymentStatus}</Td></Tr>}/>}
function SalesTable({title,subtitle,rows,loading,headers,cells}){return <div><PageHeader title={title} subtitle={subtitle}/><div className="rounded-2xl border border-white/80 bg-white p-5 shadow-card">{loading?<LoadingTable columns={headers.length}/>:!rows.length?<EmptyState title={`No ${title.toLowerCase()} found.`}/>:<Table><thead><tr>{headers.map(h=><Th key={h}>{h}</Th>)}</tr></thead><tbody>{rows.map(cells)}</tbody></Table>}</div></div>}
