import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { inventoryApi, productsApi } from '../../lib/masterDataApi.js';
import { useAuth } from '../../lib/AuthContext.jsx';
import { useToast } from '../../components/Toast.jsx';
import { PageHeader } from '../../components/PageHeader.jsx';
import { Button } from '../../components/Button.jsx';
import { Input } from '../../components/Input.jsx';
import { Select } from '../../components/Select.jsx';
import { Table, Th, Td, Tr } from '../../components/Table.jsx';
import { Pagination } from '../../components/Pagination.jsx';
import { formatMoney } from '../../lib/format.js';

const statuses = ['', 'IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK'];
export function InventoryPage() {
  const { user } = useAuth(); const [data, setData] = useState({ inventory: [], summary: {}, pagination: {} }); const [query, setQuery] = useState({ page: 1, limit: 20, search: '', status: '' }); const [loading, setLoading] = useState(true); const [showAdjust, setShowAdjust] = useState(false);
  const load = () => { setLoading(true); inventoryApi.list(query).then(setData).finally(() => setLoading(false)); }; useEffect(load, [query.page, query.status]);
  return <div><PageHeader title="Inventory" subtitle="Current GOODS stock, weighted cost, and stock valuation" actions={user.role === 'ADMIN' ? <Button onClick={() => setShowAdjust(true)}>Adjust Stock</Button> : null} />
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Tracked Products',data.summary.totalProducts],['Units in Stock',data.summary.totalUnits],['Low Stock',data.summary.lowStockProducts],['Out of Stock',data.summary.outOfStockProducts],['Inventory Value',formatMoney(data.summary.inventoryValue || 0)]].map(([label,value])=><div key={label} className="rounded-2xl border border-white/80 bg-white p-5 shadow-card"><p className="text-xs font-bold uppercase tracking-wide text-muted">{label}</p><p className="mt-2 text-2xl font-bold text-navy">{value ?? 0}</p></div>)}</div>
    <div className="rounded-2xl border border-white/80 bg-white p-5 shadow-card"><div className="mb-4 flex flex-wrap gap-3"><Input value={query.search} placeholder="Search products…" onChange={e=>setQuery({...query,search:e.target.value,page:1})}/><Select value={query.status} onChange={e=>setQuery({...query,status:e.target.value,page:1})}>{statuses.map(x=><option key={x} value={x}>{x ? x.replaceAll('_',' ') : 'All statuses'}</option>)}</Select><Button variant="secondary" onClick={load}>Search</Button><Link className="ml-auto text-sm font-bold text-indigo" to="/inventory/movements">Movement history →</Link></div>
      <Table minWidth="800px"><thead><tr><Th>Product</Th><Th>Type</Th><Th>Current Stock</Th><Th>Avg. Cost</Th><Th>Stock Value</Th><Th>Status</Th></tr></thead><tbody>{loading?<Tr><Td colSpan="6">Loading inventory…</Td></Tr>:data.inventory.map(item=><Tr key={item.id}><Td first><Link className="font-semibold text-indigo" to={`/inventory/products/${item.id}`}>{item.name}</Link></Td><Td>{item.type}</Td><Td>{item.quantity}</Td><Td>{formatMoney(item.averageCost)}</Td><Td>{formatMoney(item.stockValue)}</Td><Td last><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.stockStatus==='OUT_OF_STOCK'?'bg-danger/10 text-danger':item.stockStatus==='LOW_STOCK'?'bg-amber-100 text-amber-700':'bg-success/10 text-success'}`}>{item.stockStatus.replaceAll('_',' ')}</span></Td></Tr>)}</tbody></Table><Pagination pagination={data.pagination} onPageChange={page=>setQuery({...query,page})}/></div>{showAdjust&&<Adjustment onClose={()=>setShowAdjust(false)} onSaved={()=>{setShowAdjust(false);load();}}/>}</div>;
}
function Adjustment({onClose,onSaved}) { const {user}=useAuth(); const {notify}=useToast(); const [products,setProducts]=useState([]),[form,setForm]=useState({productId:'',direction:'IN',quantity:'',reason:'',notes:''}),[current,setCurrent]=useState(null),[saving,setSaving]=useState(false); useEffect(()=>{productsApi.list({status:'ACTIVE',limit:100}).then(x=>setProducts((x.products||[]).filter(p=>p.type==='GOODS')));},[]); useEffect(()=>{if(form.productId)inventoryApi.detail(form.productId).then(x=>setCurrent(x.inventory));},[form.productId]); if(user.role!=='ADMIN') return <div className="fixed inset-0 z-50 grid place-items-center bg-navy/30 p-4"><div className="rounded-2xl bg-white p-6 shadow-soft">Only Administrators can adjust stock.<div className="mt-4"><Button onClick={onClose}>Close</Button></div></div></div>; const expected=current ? Number(current.quantity)+(form.direction==='IN'?Number(form.quantity||0):-Number(form.quantity||0)) : null; const save=async()=>{setSaving(true);try{await inventoryApi.adjust(form);notify('Stock adjustment recorded.');onSaved();}catch(e){notify(e.message||'Could not adjust stock.',{tone:'error'});}finally{setSaving(false);}}; return <div className="fixed inset-0 z-50 overflow-y-auto bg-navy/30 p-4"><div className="mx-auto mt-16 max-w-lg rounded-2xl bg-white p-6 shadow-soft"><h2 className="text-xl font-bold text-navy">Stock Adjustment</h2><p className="mt-1 text-sm text-muted">Every change is recorded in the immutable stock ledger.</p><div className="mt-5 space-y-4"><Select value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})}><option value="">Select GOODS product</option>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</Select><div className="grid grid-cols-2 gap-3"><Select value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}><option value="IN">Adjustment In</option><option value="OUT">Adjustment Out</option></Select><Input type="number" min="0.01" placeholder="Quantity" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></div><Input placeholder="Reason (required)" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><Input placeholder="Notes / reference" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/>{current&&<div className="rounded-xl bg-page p-3 text-sm">Current stock: <b>{current.quantity}</b> · Expected new stock: <b className={expected<0?'text-danger':'text-success'}>{expected}</b></div>}</div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={saving||!form.productId||!form.quantity||!form.reason} onClick={save}>Confirm Adjustment</Button></div></div></div>; }
