export const initialMockData = {
  contacts: [
    {
      id: 'cnt-1',
      name: 'Horizon Tech Solutions',
      type: 'CUSTOMER',
      email: 'accounting@horizontech.io',
      phone: '+1 (555) 234-5678',
      city: 'New York, NY',
      taxId: 'US-8472910',
      paymentTerms: '30 Days',
      balance: 5250.0,
      status: 'ACTIVE',
    },
    {
      id: 'cnt-2',
      name: 'Apex Architects & Design',
      type: 'CUSTOMER',
      email: 'finance@apexarch.com',
      phone: '+1 (555) 345-6789',
      city: 'Chicago, IL',
      taxId: 'US-1029384',
      paymentTerms: '15 Days',
      balance: 0.0,
      status: 'ACTIVE',
    },
    {
      id: 'cnt-3',
      name: 'Metro Coworking Spaces',
      type: 'CUSTOMER',
      email: 'billing@metrocowork.com',
      phone: '+1 (555) 456-7890',
      city: 'Seattle, WA',
      taxId: 'US-9283741',
      paymentTerms: '30 Days',
      balance: 6200.0,
      status: 'ACTIVE',
    },
    {
      id: 'cnt-4',
      name: 'TimberCraft Hardwood Suppliers',
      type: 'VENDOR',
      email: 'orders@timbercraft.com',
      phone: '+1 (555) 987-6543',
      city: 'Portland, OR',
      taxId: 'US-5544332',
      paymentTerms: '30 Days',
      balance: 7800.0,
      status: 'ACTIVE',
    },
    {
      id: 'cnt-5',
      name: 'SteelForm Hardware Ltd.',
      type: 'VENDOR',
      email: 'supply@steelform.com',
      phone: '+1 (555) 876-5432',
      city: 'Pittsburgh, PA',
      taxId: 'US-4433221',
      paymentTerms: '30 Days',
      balance: 0.0,
      status: 'ACTIVE',
    },
    {
      id: 'cnt-6',
      name: 'Global Logistics & Freight',
      type: 'VENDOR',
      email: 'invoicing@globallogistics.com',
      phone: '+1 (555) 765-4321',
      city: 'Dallas, TX',
      taxId: 'US-3322110',
      paymentTerms: 'Immediate',
      balance: 900.0,
      status: 'ACTIVE',
    },
  ],

  products: [
    {
      id: 'prd-1',
      name: 'Executive Mahogany Desk',
      sku: 'DESK-MAH-01',
      category: 'Desks & Workstations',
      salesPrice: 1250.0,
      costPrice: 650.0,
      taxPercent: 10,
      stockQuantity: 24,
      uom: 'Units',
      status: 'ACTIVE',
    },
    {
      id: 'prd-2',
      name: 'Ergonomic Mesh Task Chair',
      sku: 'CHR-ERGO-02',
      category: 'Seating',
      salesPrice: 420.0,
      costPrice: 190.0,
      taxPercent: 10,
      stockQuantity: 65,
      uom: 'Units',
      status: 'ACTIVE',
    },
    {
      id: 'prd-3',
      name: '12-Person Boardroom Conference Table',
      sku: 'TBL-CONF-12',
      category: 'Conference Furniture',
      salesPrice: 2800.0,
      costPrice: 1400.0,
      taxPercent: 10,
      stockQuantity: 12,
      uom: 'Units',
      status: 'ACTIVE',
    },
    {
      id: 'prd-4',
      name: 'Acoustic Modular Lounge Sofa',
      sku: 'SOFA-MOD-04',
      category: 'Lounge & Reception',
      salesPrice: 1650.0,
      costPrice: 850.0,
      taxPercent: 10,
      stockQuantity: 18,
      uom: 'Units',
      status: 'ACTIVE',
    },
    {
      id: 'prd-5',
      name: 'Steel 4-Drawer Lateral Credenza',
      sku: 'STOR-CRD-05',
      category: 'Storage',
      salesPrice: 580.0,
      costPrice: 290.0,
      taxPercent: 10,
      stockQuantity: 40,
      uom: 'Units',
      status: 'ACTIVE',
    },
    {
      id: 'prd-6',
      name: 'Premium Cable Management Spine',
      sku: 'ACC-SPN-06',
      category: 'Accessories',
      salesPrice: 75.0,
      costPrice: 25.0,
      taxPercent: 10,
      stockQuantity: 120,
      uom: 'Units',
      status: 'ACTIVE',
    },
  ],

  accounts: [
    {
      id: 'acc-1',
      code: '101000',
      name: 'Cash on Hand',
      type: 'ASSET',
      currency: 'USD',
      balance: 18450.0,
      reconcilable: true,
      status: 'ACTIVE',
    },
    {
      id: 'acc-2',
      code: '102000',
      name: 'Operating Bank Account (Chase)',
      type: 'ASSET',
      currency: 'USD',
      balance: 124800.0,
      reconcilable: true,
      status: 'ACTIVE',
    },
    {
      id: 'acc-3',
      code: '120000',
      name: 'Accounts Receivable (Debtors)',
      type: 'ASSET',
      currency: 'USD',
      balance: 46200.0,
      reconcilable: true,
      status: 'ACTIVE',
    },
    {
      id: 'acc-4',
      code: '130000',
      name: 'Furniture Inventory',
      type: 'ASSET',
      currency: 'USD',
      balance: 68400.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-5',
      code: '150000',
      name: 'Office Equipment & Fixtures',
      type: 'ASSET',
      currency: 'USD',
      balance: 185000.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-6',
      code: '200000',
      name: 'Accounts Payable (Creditors)',
      type: 'LIABILITY',
      currency: 'USD',
      balance: 29650.0,
      reconcilable: true,
      status: 'ACTIVE',
    },
    {
      id: 'acc-7',
      code: '220000',
      name: 'Sales Tax Payable',
      type: 'LIABILITY',
      currency: 'USD',
      balance: 6800.0,
      reconcilable: true,
      status: 'ACTIVE',
    },
    {
      id: 'acc-8',
      code: '250000',
      name: 'Commercial Bank Loan',
      type: 'LIABILITY',
      currency: 'USD',
      balance: 50000.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-9',
      code: '300000',
      name: "Common Stock & Owner's Capital",
      type: 'EQUITY',
      currency: 'USD',
      balance: 200000.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-10',
      code: '320000',
      name: 'Retained Earnings',
      type: 'EQUITY',
      currency: 'USD',
      balance: 95000.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-11',
      code: '400000',
      name: 'Commercial Furniture Sales',
      type: 'INCOME',
      currency: 'USD',
      balance: 182400.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-12',
      code: '500000',
      name: 'Cost of Goods Sold (COGS)',
      type: 'EXPENSE',
      currency: 'USD',
      balance: 94500.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-13',
      code: '600000',
      name: 'Showroom & Office Rent',
      type: 'EXPENSE',
      currency: 'USD',
      balance: 18000.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-14',
      code: '610000',
      name: 'Staff Salaries & Benefits',
      type: 'EXPENSE',
      currency: 'USD',
      balance: 34500.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-15',
      code: '620000',
      name: 'Utilities & Communications',
      type: 'EXPENSE',
      currency: 'USD',
      balance: 3200.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
    {
      id: 'acc-16',
      code: '630000',
      name: 'Digital Marketing & Showroom Ads',
      type: 'EXPENSE',
      currency: 'USD',
      balance: 5800.0,
      reconcilable: false,
      status: 'ACTIVE',
    },
  ],

  journals: [
    {
      id: 'jnl-1',
      name: 'Customer Invoices',
      code: 'INV',
      type: 'SALE',
      defaultAccount: '120000',
      shortCode: 'INV',
    },
    {
      id: 'jnl-2',
      name: 'Vendor Bills',
      code: 'BILL',
      type: 'PURCHASE',
      defaultAccount: '200000',
      shortCode: 'BILL',
    },
    {
      id: 'jnl-3',
      name: 'Chase Operating Bank',
      code: 'BNK1',
      type: 'BANK',
      defaultAccount: '102000',
      shortCode: 'BNK',
    },
    {
      id: 'jnl-4',
      name: 'Cash Register Drawer',
      code: 'CSH1',
      type: 'CASH',
      defaultAccount: '101000',
      shortCode: 'CSH',
    },
    {
      id: 'jnl-5',
      name: 'Miscellaneous Operations',
      code: 'MISC',
      type: 'GENERAL',
      defaultAccount: '320000',
      shortCode: 'MISC',
    },
  ],

  analyticAccounts: [
    {
      id: 'ana-1',
      name: 'HQ Flagship Showroom',
      code: 'AA-SHOWROOM',
      partner: 'Internal',
      budget: 50000.0,
      spent: 32400.0,
      status: 'ACTIVE',
    },
    {
      id: 'ana-2',
      name: 'Tech Hub Furnishing Contract',
      code: 'AA-TECH-HUB',
      partner: 'Horizon Tech Solutions',
      budget: 85000.0,
      spent: 61200.0,
      status: 'ACTIVE',
    },
    {
      id: 'ana-3',
      name: 'Annual Ergonomic Marketing Campaign',
      code: 'AA-MKT-2026',
      partner: 'Internal',
      budget: 25000.0,
      spent: 14200.0,
      status: 'ACTIVE',
    },
    {
      id: 'ana-4',
      name: 'Warehouse Automation & Racks',
      code: 'AA-WH-AUTO',
      partner: 'Internal',
      budget: 35000.0,
      spent: 12800.0,
      status: 'ACTIVE',
    },
  ],

  budgets: [
    {
      id: 'bdg-1',
      name: 'FY2026 Commercial Operations Budget',
      dateFrom: '2026-01-01',
      dateTo: '2026-12-31',
      totalPlanned: 196000.0,
      totalPractical: 120600.0,
      lines: [
        {
          id: 'line-1',
          name: 'Showroom Lease & Upkeep',
          account: '600000 - Showroom & Office Rent',
          plannedAmount: 36000.0,
          practicalAmount: 18000.0,
        },
        {
          id: 'line-2',
          name: 'Tech Hub Fit-out Execution',
          account: '500000 - Cost of Goods Sold',
          plannedAmount: 85000.0,
          practicalAmount: 61200.0,
        },
        {
          id: 'line-3',
          name: 'Showroom Interior Remodel',
          account: '150000 - Office Equipment & Fixtures',
          plannedAmount: 50000.0,
          practicalAmount: 32400.0,
        },
        {
          id: 'line-4',
          name: 'Digital Advertising & Press',
          account: '630000 - Marketing & Ads',
          plannedAmount: 25000.0,
          practicalAmount: 14200.0,
        },
      ],
    },
  ],

  salesOrders: [
    {
      id: 'so-1001',
      orderNumber: 'SO/2026/0001',
      customerId: 'cnt-1',
      customerName: 'Horizon Tech Solutions',
      orderDate: '2026-02-15',
      status: 'CONFIRMED',
      invoiceStatus: 'TO INVOICE',
      paymentTerms: '30 Days',
      items: [
        {
          productId: 'prd-1',
          productName: 'Executive Mahogany Desk',
          quantity: 4,
          unitPrice: 1250.0,
          taxPercent: 10,
          subtotal: 5000.0,
        },
        {
          productId: 'prd-2',
          productName: 'Ergonomic Mesh Task Chair',
          quantity: 6,
          unitPrice: 420.0,
          taxPercent: 10,
          subtotal: 2520.0,
        },
      ],
      subtotal: 7520.0,
      tax: 752.0,
      total: 8272.0,
    },
    {
      id: 'so-1002',
      orderNumber: 'SO/2026/0002',
      customerId: 'cnt-2',
      customerName: 'Apex Architects & Design',
      orderDate: '2026-02-18',
      status: 'DONE',
      invoiceStatus: 'FULLY INVOICED',
      paymentTerms: '15 Days',
      items: [
        {
          productId: 'prd-3',
          productName: '12-Person Boardroom Conference Table',
          quantity: 2,
          unitPrice: 2800.0,
          taxPercent: 10,
          subtotal: 5600.0,
        },
        {
          productId: 'prd-4',
          productName: 'Acoustic Modular Lounge Sofa',
          quantity: 4,
          unitPrice: 1650.0,
          taxPercent: 10,
          subtotal: 6600.0,
        },
      ],
      subtotal: 12200.0,
      tax: 1220.0,
      total: 13420.0,
    },
    {
      id: 'so-1003',
      orderNumber: 'SO/2026/0003',
      customerId: 'cnt-3',
      customerName: 'Metro Coworking Spaces',
      orderDate: '2026-02-24',
      status: 'QUOTATION',
      invoiceStatus: 'NOTHING TO INVOICE',
      paymentTerms: '30 Days',
      items: [
        {
          productId: 'prd-2',
          productName: 'Ergonomic Mesh Task Chair',
          quantity: 12,
          unitPrice: 420.0,
          taxPercent: 10,
          subtotal: 5040.0,
        },
      ],
      subtotal: 5040.0,
      tax: 504.0,
      total: 5544.0,
    },
  ],

  purchaseOrders: [
    {
      id: 'po-2001',
      orderNumber: 'PO/2026/0001',
      vendorId: 'cnt-4',
      vendorName: 'TimberCraft Hardwood Suppliers',
      orderDate: '2026-02-10',
      status: 'PURCHASE ORDER',
      billStatus: 'WAITING BILLS',
      paymentTerms: '30 Days',
      items: [
        {
          productId: 'prd-1',
          productName: 'Executive Mahogany Desk',
          quantity: 10,
          unitPrice: 650.0,
          taxPercent: 0,
          subtotal: 6500.0,
        },
      ],
      subtotal: 6500.0,
      tax: 0.0,
      total: 6500.0,
    },
    {
      id: 'po-2002',
      orderNumber: 'PO/2026/0002',
      vendorId: 'cnt-5',
      vendorName: 'SteelForm Hardware Ltd.',
      orderDate: '2026-02-12',
      status: 'PURCHASE ORDER',
      billStatus: 'FULLY BILLED',
      paymentTerms: '30 Days',
      items: [
        {
          productId: 'prd-5',
          productName: 'Steel 4-Drawer Lateral Credenza',
          quantity: 15,
          unitPrice: 290.0,
          taxPercent: 0,
          subtotal: 4350.0,
        },
      ],
      subtotal: 4350.0,
      tax: 0.0,
      total: 4350.0,
    },
    {
      id: 'po-2003',
      orderNumber: 'PO/2026/0003',
      vendorId: 'cnt-6',
      vendorName: 'Global Logistics & Freight',
      orderDate: '2026-02-20',
      status: 'RFQ',
      billStatus: 'NOTHING TO BILL',
      paymentTerms: 'Immediate',
      items: [
        {
          productId: 'prd-6',
          productName: 'Premium Cable Management Spine',
          quantity: 40,
          unitPrice: 25.0,
          taxPercent: 0,
          subtotal: 1000.0,
        },
      ],
      subtotal: 1000.0,
      tax: 0.0,
      total: 1000.0,
    },
  ],

  invoices: [
    {
      id: 'inv-3001',
      invoiceNumber: 'INV/2026/0001',
      salesOrderId: 'so-1002',
      customerId: 'cnt-2',
      customerName: 'Apex Architects & Design',
      invoiceDate: '2026-02-19',
      dueDate: '2026-03-06',
      paymentTerms: '15 Days',
      status: 'PAID',
      items: [
        {
          productId: 'prd-3',
          productName: '12-Person Boardroom Conference Table',
          quantity: 2,
          unitPrice: 2800.0,
          taxPercent: 10,
          subtotal: 5600.0,
        },
        {
          productId: 'prd-4',
          productName: 'Acoustic Modular Lounge Sofa',
          quantity: 4,
          unitPrice: 1650.0,
          taxPercent: 10,
          subtotal: 6600.0,
        },
      ],
      subtotal: 12200.0,
      tax: 1220.0,
      total: 13420.0,
      paid: 13420.0,
      outstanding: 0.0,
    },
    {
      id: 'inv-3002',
      invoiceNumber: 'INV/2026/0002',
      salesOrderId: 'so-1001',
      customerId: 'cnt-1',
      customerName: 'Horizon Tech Solutions',
      invoiceDate: '2026-02-22',
      dueDate: '2026-03-24',
      paymentTerms: '30 Days',
      status: 'PARTIALLY_PAID',
      items: [
        {
          productId: 'prd-1',
          productName: 'Executive Mahogany Desk',
          quantity: 4,
          unitPrice: 1250.0,
          taxPercent: 10,
          subtotal: 5000.0,
        },
        {
          productId: 'prd-2',
          productName: 'Ergonomic Mesh Task Chair',
          quantity: 6,
          unitPrice: 420.0,
          taxPercent: 10,
          subtotal: 2520.0,
        },
      ],
      subtotal: 7520.0,
      tax: 752.0,
      total: 8272.0,
      paid: 3000.0,
      outstanding: 5272.0,
    },
    {
      id: 'inv-3003',
      invoiceNumber: 'INV/2026/0003',
      salesOrderId: null,
      customerId: 'cnt-3',
      customerName: 'Metro Coworking Spaces',
      invoiceDate: '2026-02-25',
      dueDate: '2026-03-27',
      paymentTerms: '30 Days',
      status: 'POSTED',
      items: [
        {
          productId: 'prd-5',
          productName: 'Steel 4-Drawer Lateral Credenza',
          quantity: 10,
          unitPrice: 580.0,
          taxPercent: 10,
          subtotal: 5800.0,
        },
      ],
      subtotal: 5800.0,
      tax: 580.0,
      total: 6380.0,
      paid: 0.0,
      outstanding: 6380.0,
    },
  ],

  vendorBills: [
    {
      id: 'bill-4001',
      billNumber: 'BILL/2026/0001',
      purchaseOrderId: 'po-2002',
      vendorId: 'cnt-5',
      vendorName: 'SteelForm Hardware Ltd.',
      billDate: '2026-02-14',
      dueDate: '2026-03-16',
      paymentTerms: '30 Days',
      status: 'PAID',
      items: [
        {
          productId: 'prd-5',
          productName: 'Steel 4-Drawer Lateral Credenza',
          quantity: 15,
          unitPrice: 290.0,
          taxPercent: 0,
          subtotal: 4350.0,
        },
      ],
      subtotal: 4350.0,
      tax: 0.0,
      total: 4350.0,
      paid: 4350.0,
      outstanding: 0.0,
    },
    {
      id: 'bill-4002',
      billNumber: 'BILL/2026/0002',
      purchaseOrderId: 'po-2001',
      vendorId: 'cnt-4',
      vendorName: 'TimberCraft Hardwood Suppliers',
      billDate: '2026-02-18',
      dueDate: '2026-03-20',
      paymentTerms: '30 Days',
      status: 'POSTED',
      items: [
        {
          productId: 'prd-1',
          productName: 'Executive Mahogany Desk',
          quantity: 10,
          unitPrice: 650.0,
          taxPercent: 0,
          subtotal: 6500.0,
        },
      ],
      subtotal: 6500.0,
      tax: 0.0,
      total: 6500.0,
      paid: 0.0,
      outstanding: 6500.0,
    },
    {
      id: 'bill-4003',
      billNumber: 'BILL/2026/0003',
      purchaseOrderId: null,
      vendorId: 'cnt-6',
      vendorName: 'Global Logistics & Freight',
      billDate: '2026-02-22',
      dueDate: '2026-02-22',
      paymentTerms: 'Immediate',
      status: 'PARTIALLY_PAID',
      items: [
        {
          productId: 'prd-6',
          productName: 'Interstate Freight & Handling',
          quantity: 1,
          unitPrice: 1400.0,
          taxPercent: 0,
          subtotal: 1400.0,
        },
      ],
      subtotal: 1400.0,
      tax: 0.0,
      total: 1400.0,
      paid: 500.0,
      outstanding: 900.0,
    },
  ],

  payments: [
    {
      id: 'pay-5001',
      paymentNumber: 'PAY/2026/0001',
      type: 'INBOUND',
      targetType: 'INVOICE',
      targetId: 'inv-3001',
      targetNumber: 'INV/2026/0001',
      partnerName: 'Apex Architects & Design',
      amount: 13420.0,
      method: 'Bank',
      journalId: 'jnl-3',
      journalName: 'Chase Operating Bank',
      date: '2026-02-20',
      memo: 'Full settlement for invoice INV/2026/0001',
    },
    {
      id: 'pay-5002',
      paymentNumber: 'PAY/2026/0002',
      type: 'INBOUND',
      targetType: 'INVOICE',
      targetId: 'inv-3002',
      targetNumber: 'INV/2026/0002',
      partnerName: 'Horizon Tech Solutions',
      amount: 3000.0,
      method: 'Bank',
      journalId: 'jnl-3',
      journalName: 'Chase Operating Bank',
      date: '2026-02-23',
      memo: 'Initial deposit on order SO001',
    },
    {
      id: 'pay-5003',
      paymentNumber: 'PAY/2026/0003',
      type: 'OUTBOUND',
      targetType: 'BILL',
      targetId: 'bill-4001',
      targetNumber: 'BILL/2026/0001',
      partnerName: 'SteelForm Hardware Ltd.',
      amount: 4350.0,
      method: 'Bank',
      journalId: 'jnl-3',
      journalName: 'Chase Operating Bank',
      date: '2026-02-16',
      memo: 'Electronic funds transfer for credenza raw steel',
    },
    {
      id: 'pay-5004',
      paymentNumber: 'PAY/2026/0004',
      type: 'OUTBOUND',
      targetType: 'BILL',
      targetId: 'bill-4003',
      targetNumber: 'BILL/2026/0003',
      partnerName: 'Global Logistics & Freight',
      amount: 500.0,
      method: 'Cash',
      journalId: 'jnl-4',
      journalName: 'Cash Register Drawer',
      date: '2026-02-22',
      memo: 'Cash advance on freight delivery',
    },
  ],
};
