import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button } from '../../components/Button.jsx';
import { PageHeader } from '../../components/PageHeader.jsx';
import { Table, Td, Th, Tr } from '../../components/Table.jsx';
import { formatDate, formatMoney } from '../../lib/format.js';
import { journalEntriesApi } from '../../lib/masterDataApi.js';
import { useToast } from '../../components/Toast.jsx';
export function JournalEntryDetailPage(){const {id}=useParams();const [entry,setEntry]=useState(null);const nav=useNavigate();const {notify}=useToast();const load=()=>{journalEntriesApi.get(id).then(d=>setEntry(d.journalEntry));};useEffect(load,[id]);if(!entry)return <div className="rounded-2xl bg-white p-8 shadow-card">Loading Journal Entry…</div>;async function act(type){if(!window.confirm(type==='post'?'Post this Journal Entry? Once posted, it cannot be edited.':'Cancel this draft Journal Entry?'))return;try{await journalEntriesApi[type](id);notify(type==='post'?'Journal Entry posted successfully.':'Journal Entry cancelled.');load();}catch(e){notify(e.message,{tone:'error'});}}return <div><PageHeader title={entry.entryNumber} subtitle={`${entry.status} · ${formatDate(entry.entryDate)}`} actions={<><Button variant="secondary" onClick={()=>nav('/accounting/journal-entries')}>Back</Button>{entry.status==='DRAFT'&&<><Button variant="secondary" onClick={()=>act('cancel')}>Cancel Draft</Button><Button onClick={()=>act('post')}>Post Entry</Button></>}</>}/><div className="rounded-2xl border border-white/80 bg-white p-6 shadow-card"><div className="mb-6 grid gap-3 text-sm sm:grid-cols-3"><p><b>Journal:</b> {entry.journalName}</p><p><b>Reference:</b> {entry.reference||'—'}</p><p><b>Created by:</b> {entry.createdBy}</p><p><b>Description:</b> {entry.description||'—'}</p><p><b>Posted by:</b> {entry.postedBy||'—'}</p><p><b>Posted at:</b> {formatDate(entry.postedAt)}</p></div><Table><thead><tr><Th>Account</Th><Th>Description</Th><Th>Debit</Th><Th>Credit</Th><Th>Analytic Account</Th></tr></thead><tbody>{entry.lines.map(l=><Tr key={l.id}><Td first className="font-semibold">{l.accountCode} · {l.accountName}</Td><Td>{l.description||'—'}</Td><Td>{formatMoney(l.debit)}</Td><Td>{formatMoney(l.credit)}</Td><Td last>{l.analyticAccountName||'—'}</Td></Tr>)}</tbody></Table><div className="mt-5 flex justify-end gap-6 font-bold"><span>Total Debit: {formatMoney(entry.totalDebit)}</span><span>Total Credit: {formatMoney(entry.totalCredit)}</span></div></div></div>}
